### ISSUE TITLE
Test dependencies config

### ISSUE THREAD

**Issue by mbarbin** [fpottier/bbst#1]
Thanks for `baby`! I was browsing the library and came across that note from the `dune-project` file about tests dependencies. I wasn't able to reproduce a build issue when joining the two conditionals together such as in the following (same in `hector`):

```diff
diff --git a/dune-project b/dune-project
index e05a9ad..2fd8f62 100644
--- a/dune-project
+++ b/dune-project
@@ -17,10 +17,9 @@
   (depends
     (ocaml (>= 4.14))
     (cppo (>= 1.8.0))
-    (monolith (>= 20241126))
+    (monolith
+     (and
+       :with-test
+       (>= 20241126)))
   )
 )
-;; monolith is needed only for testing, but I do not know
-;; how to say both :with-test and (>= 20241126).
-;; dune accepts either indication,
-;; but not both indications together.
```

Do you get issues further down, such as in the CI execution? I don't have a horse in the race, I was simply curious and willing to help. I am planning to perhaps experiment with `flatunionfind` in my projects in the future (which currently inherits the `monolith` dependency via `hector`). Thank you!

**Comment by fpottier** [comment]
Hello and thanks! I did not know about `and`. I have fixed the problem in `baby` and in `hector`.

**Comment by mbarbin** [comment]
Thank you for the fix, and the submission to the opam repo!
